export const galeri = [
    { id: 1, url: "araba-1.jpg" },
    { id: 2, url: "araba-2.jpg" },
    { id: 3, url: "araba-3.jpg" },
    { id: 4, url: "araba-4.jpg" },
    { id: 5, url: "araba-5.jpg" },
    { id: 6, url: "araba-6.jpg" },
    { id: 7, url: "araba-7.jpg" },
    { id: 8, url: "araba-8.jpg" },
    { id: 9, url: "araba-9.jpg" },
    { id: 10, url: "araba-10.jpg" },
    { id: 11, url: "araba-11.jpg" },
    { id: 12, url: "araba-12.jpg" },
    { id: 13, url: "araba-13.jpg" },
    { id: 14, url: "araba-14.jpg" },
    { id: 15, url: "araba-15.jpg" },
    { id: 16, url: "araba-16.jpg" },
    { id: 17, url: "araba-17.jpg" },
    { id: 18, url: "araba-18.jpg" },
    { id: 19, url: "araba-19.jpg" },
    { id: 20, url: "araba-20.jpg" },
    { id: 21, url: "araba-21.jpg" },
    { id: 22, url: "araba-22.jpg" },
    { id: 23, url: "araba-23.jpg" },
    { id: 24, url: "araba-24.jpg" },
    { id: 25, url: "araba-25.jpg" },
    { id: 26, url: "araba-26.jpg" },
    { id: 27, url: "araba-27.jpg" },
    { id: 28, url: "araba-28.jpg" },
    { id: 29, url: "araba-29.jpg" },
    { id: 30, url: "araba-30.jpg" },
    { id: 31, url: "araba-31.jpg" },
    { id: 32, url: "araba-32.jpg" }

];
